#!/bin/bash
# Grub-autoconfig module
grubconf() {
grubadd=$1
grubdefaultline=$(grep GRUB_CMDLINE_LINUX_DEFAULT /etc/default/grub)
grubdefault=$(echo "$grubdefaultline" | sed s/'GRUB_CMDLINE_LINUX_DEFAULT='//g | sed s/'"'//g)
grubtext='GRUB_CMDLINE_LINUX_DEFAULT="'${grubdefault}' '${grubadd}'"'
sed -i s/"$grubdefaultline"/"$grubtext"/g /etc/default/grub
update-grub
}
# Syntax
# grubconf ["Something you want to add to GRUB_CMDLINE_LINUX_DEFAULT"]
# Example:
# sudo bash grub-autoconfig "amd_iommu=on"
# Example result:
# 
exit
